#!groovy
//import java.text.SimpleDateFormat 
//import java.util.Date
//proposed method: 
//1. use release plugin to prepare a build. mvn release:prepare -Dusername=krystedt
//2. have a jenkins job to checkout tag and copy to test deploy dir.
//3. when tested merge tag with master and have another jenkins job that sets the production properties.
//might start without jenkins. 
pipeline {
    agent any
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
               
            }
        }
        stage ('Build') {
            steps {
                sh 'cd Test && mvn -Dmaven.test.failure.ignore=true -Demailwarnings.enabled=true clean install' 
            }
            post {
                success {
                    junit 'Test/target/surefire-reports/**/*.xml' 
                }
            }
        }
        stage('Deploy') {
            steps {
            	//might need to use stash/unstash in build step..
            	script {
            	 	Date date = new Date()
            	 	def dateString = date.format ('yyyy-MM-dd')
                	sh "mkdir /home/kalle/temp/${dateString} && cp Test/target/*.war /home/kalle/temp/${dateString}/ProdentusApp.war" 
                } 
            }
        }
    }
}
