pipeline {
    agent any
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage ('Build') {
            steps {
                sh 'cd Test && mvn -Dmaven.test.failure.ignore=true clean install' 
            }
            post {
                success {
                    junit 'Test/target/surefire-reports/**/*.xml' 
                }
            }
        }
        stage('Deploy') {
            steps {
            	//might use environment variables to do a simple cp from absolute path to deploy dir
            	//might be better to use stash in build step..
                sh 'cp Test/target/*.war /home/kalle/temp/ProdentusApp.war' 
            }
        }
    }
}
